# Numpy quick reference

## Initial setup

In [1]:
import numpy as np

## Array creation

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.array([(1.5,2,3), (4,5,6)], dtype = float)

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [4]:
np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype = float)

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((2,3,4), dtype=np.float32)

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

In [7]:
np.arange(10, 25, 5)

array([10, 15, 20])

In [8]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [9]:
np.full((2,3), 7)

array([[7, 7, 7],
       [7, 7, 7]])

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random variables initialization

In [11]:
np.random.random((2,3))

array([[0.97003657, 0.74272493, 0.96802314],
       [0.05436911, 0.69463146, 0.71970063]])

In [12]:
np.random.randint(10, 20, (2,5))

array([[15, 10, 11, 17, 13],
       [10, 10, 12, 17, 17]])

In [13]:
np.random.normal(size=10)

array([ 0.10901958,  1.539097  , -0.89894313,  0.14346146, -0.65868685,
       -0.64456648,  1.23946721,  1.70116409,  1.51177755,  1.38266418])

In [14]:
mean = 10
std = 3
np.random.normal(mean, std, 5)

array([9.21280769, 8.89401651, 8.00252775, 8.51585531, 6.98027599])

In [15]:
np.bool
np.int16
np.int32
np.uint16
np.uint32
np.float # Same than np.float64 
np.float32
np.float64
np.complex
np.string_
np.object # Python object

/home/david/anaconda3/envs/ml37/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.
/home/david/anaconda3/envs/ml37/lib/python3.7/site-packages/ipykernel_launcher.py:6: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  
/home/david/anaconda3/envs/ml37/li

object

## Array inspection

In [16]:
array = np.array([(1.5,2,3), (4,5,6)], dtype = float)
array

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [17]:
array.shape

(2, 3)

In [18]:
len(array)

2

In [19]:
array.ndim

2

In [20]:
array.size

6

In [21]:
array.dtype

dtype('float64')

In [22]:
array.dtype.name

'float64'

In [23]:
array.astype(np.float32)

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]], dtype=float32)

## Array reshape

In [24]:
a = np.linspace(1, 6, 6)

print(a)
print(a.shape)

[1. 2. 3. 4. 5. 6.]
(6,)


In [25]:
a.reshape(2, 3)
print(a.shape)

(6,)


In [26]:
b = a.reshape(2, 3)
print(b)
print(b.shape)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)


## Arithmetic operations

In [27]:
a = np.random.random((2,3))
b = np.random.random((2,3))

a + b

array([[0.92389638, 0.8769809 , 1.45496114],
       [1.42363966, 1.10186313, 1.05305782]])

In [28]:
a + 2 * b

array([[1.52639019, 0.89440942, 1.99133834],
       [2.15592375, 1.50090385, 1.78636129]])

In [29]:
np.add(a, b)

array([[0.92389638, 0.8769809 , 1.45496114],
       [1.42363966, 1.10186313, 1.05305782]])

In [30]:
np.subtract(a, b)

array([[-0.28109124,  0.84212387,  0.38220674],
       [-0.0409285 ,  0.3037817 , -0.41354913]])

In [31]:
np.multiply(a, b)

array([[0.19364306, 0.01498073, 0.49270748],
       [0.50626869, 0.28045476, 0.23447697]])

In [32]:
np.divide(a, b)

array([[ 0.53345373, 49.31872743,  1.71257082],
       [ 0.94410844,  1.76127994,  0.43604641]])

In [33]:
np.exp(a)

array([[1.37906064, 2.36210314, 2.5057396 ],
       [1.99642001, 2.01944438, 1.37678951]])

In [34]:
np.sqrt(a)

array([[0.56692378, 0.92712048, 0.95842785],
       [0.83147795, 0.83834504, 0.56546825]])

In [35]:
np.sin(a)

array([[0.31589762, 0.75755045, 0.79474294],
       [0.63758209, 0.64637382, 0.31433337]])

In [36]:
np.cos(a)

array([[0.94879328, 0.65277662, 0.60694617],
       [0.77038243, 0.76302089, 0.94931266]])

In [37]:
np.log(a)

array([[-1.13506083, -0.15134351, -0.08492199],
       [-0.369101  , -0.35265103, -1.14020225]])

In [38]:
np.dot(a, b.T)

array([[0.70133126, 1.25195518],
       [0.60029555, 1.02120042]])

## Comparisons

In [39]:
a == b

array([[False, False, False],
       [False, False, False]])

In [40]:
a > 0.5

array([[False,  True,  True],
       [ True,  True, False]])

In [41]:
np.equal(a, b)

array([[False, False, False],
       [False, False, False]])

In [42]:
np.array_equal(a, b)

False

## Aggregations

In [43]:
print(array)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [44]:
array.sum()

21.5

In [45]:
array.sum(axis=1) # Sum rows

array([ 6.5, 15. ])

In [46]:
array.sum(axis=0) # Sum columns

array([5.5, 7. , 9. ])

In [47]:
array.max()

6.0

In [48]:
array.max(axis=0) # Max per column

array([4., 5., 6.])

In [49]:
array.cumsum()

array([ 1.5,  3.5,  6.5, 10.5, 15.5, 21.5])

In [50]:
array.mean()

3.5833333333333335

In [51]:
array.std()

1.5920810978785667

## Array copies

In [52]:
array.view() # View on array

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [53]:
array.copy() # Deep copy

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

## Array subsetting, slicing and indexing

### Subsetting

In [54]:
a = np.arange(1,10)
print(a)
print(array)

[1 2 3 4 5 6 7 8 9]
[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [55]:
a[2]

3

In [56]:
array[1,0]

4.0

### Slicing

In [57]:
a[1:4]

array([2, 3, 4])

In [58]:
a[:4]

array([1, 2, 3, 4])

In [59]:
a[4:]

array([5, 6, 7, 8, 9])

In [60]:
a[::2]

array([1, 3, 5, 7, 9])

In [61]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [62]:
array[:1, 2]

array([3.])

### Boolean indexing

In [63]:
print(a>3)
a[a>3]

[False False False  True  True  True  True  True  True]


array([4, 5, 6, 7, 8, 9])

### Fancy indexing

In [64]:
indices = [1,3,5]
print(a)
print(a[indices])

[1 2 3 4 5 6 7 8 9]
[2 4 6]
