# Numpy quick reference

## Initial setup

In [2]:
import numpy as np

## Array creation

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
np.array([(1.5,2,3), (4,5,6)], dtype = float)

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [5]:
np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype = float)

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((2,3,4), dtype=np.float32)

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

In [9]:
np.arange(10, 25, 5)

array([10, 15, 20])

In [16]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [14]:
np.full((2,3), 7)

array([[7, 7, 7],
       [7, 7, 7]])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random variables initialization

In [18]:
np.random.random((2,3))

array([[0.83715907, 0.85613456, 0.04021312],
       [0.27177631, 0.91945395, 0.40732372]])

In [20]:
np.random.randint(10, 20, (2,5))

array([[10, 14, 12, 12, 13],
       [17, 12, 19, 19, 13]])

In [23]:
np.random.normal(size=10)

array([ 0.25396485,  0.26429597,  0.13477633,  0.90751089, -0.57304285,
       -0.91500987,  0.27691939,  0.28428315,  0.83506648, -0.5335462 ])

In [24]:
mean = 10
std = 3
np.random.normal(mean, std, 5)

array([ 6.94683239,  9.84210254,  8.1703375 , 12.60160862, 10.94860958])

In [28]:
np.bool
np.int16
np.int32
np.uint16
np.uint32
np.float # Same than np.float64 
np.float32
np.float64
np.complex
np.string_
np.object # Python object

object

## Array inspection

In [33]:
array = np.array([(1.5,2,3), (4,5,6)], dtype = float)
array

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [30]:
array.shape

(2, 3)

In [35]:
len(array)

2

In [36]:
array.ndim

2

In [37]:
array.size

6

In [38]:
array.dtype

dtype('float64')

In [39]:
array.dtype.name

'float64'

In [40]:
array.astype(np.float32)

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]], dtype=float32)

## Arithmetic operations

In [50]:
a = np.random.random((2,3))
b = np.random.random((2,3))

a + b

array([[1.20475926, 1.86534296, 1.05924151],
       [1.3462427 , 1.74196153, 1.90206505]])

In [51]:
a + 2 * b

array([[2.19871307, 2.85276021, 1.69846026],
       [1.74136884, 2.60121993, 2.87736652]])

In [52]:
np.add(a, b)

array([[1.20475926, 1.86534296, 1.05924151],
       [1.3462427 , 1.74196153, 1.90206505]])

In [54]:
np.subtract(a, b)

array([[-0.78314838, -0.10949154, -0.21919599],
       [ 0.55599043,  0.02344474, -0.04853789]])

In [56]:
np.multiply(a, b)

array([[0.20953087, 0.86687899, 0.26848643],
       [0.37581102, 0.75847008, 0.90387388]])

In [55]:
np.divide(a, b)

array([[0.21208776, 0.88911319, 0.65708768],
       [2.40712135, 1.02728485, 0.95023294]])

In [57]:
np.exp(a)

array([[1.23467211, 2.40590398, 1.5219962 ],
       [2.58859839, 2.41742551, 2.52631971]])

In [58]:
np.sqrt(a)

array([[0.45913553, 0.9369769 , 0.64809163],
       [0.97525205, 0.93952282, 0.96268561]])

In [59]:
np.sin(a)

array([[0.20924758, 0.76941558, 0.40778124],
       [0.81406448, 0.77245837, 0.79968091]])

In [60]:
np.cos(a)

array([[0.9778627 , 0.63874851, 0.91307966],
       [0.5807745 , 0.63506541, 0.60042522]])

In [61]:
np.log(a)

array([[-1.55681966, -0.1301933 , -0.86744637],
       [-0.05011865, -0.12476633, -0.07605678]])

In [63]:
np.dot(a, b.T)

array([[1.34489629, 1.2473086 ],
       [2.4093669 , 2.03815498]])

## Comparisons

In [64]:
a == b

array([[False, False, False],
       [False, False, False]])

In [68]:
a > 0.5

array([[False,  True, False],
       [ True,  True,  True]])

In [69]:
np.equal(a, b)

array([[False, False, False],
       [False, False, False]])

In [70]:
np.array_equal(a, b)

False

## Aggregations

In [74]:
print(array)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [71]:
array.sum()

21.5

In [72]:
array.sum(axis=1) # Sum rows

array([ 6.5, 15. ])

In [73]:
array.sum(axis=0) # Sum columns

array([5.5, 7. , 9. ])

In [75]:
array.max()

6.0

In [76]:
array.max(axis=0) # Max per column

array([4., 5., 6.])

In [78]:
array.cumsum()

array([ 1.5,  3.5,  6.5, 10.5, 15.5, 21.5])

In [79]:
array.mean()

3.5833333333333335

In [80]:
array.std()

1.5920810978785667

## Array copies

In [86]:
array.view() # View on array

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [87]:
array.copy() # Deep copy

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

## Array subsetting, slicing and indexing

### Subsetting

In [96]:
a = np.arange(1,10)
print(a)
print(array)

[1 2 3 4 5 6 7 8 9]
[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [97]:
a[2]

3

In [98]:
array[1,0]

4.0

### Slicing

In [101]:
a[1:4]

array([2, 3, 4])

In [103]:
a[:4]

array([1, 2, 3, 4])

In [104]:
a[4:]

array([5, 6, 7, 8, 9])

In [106]:
a[::2]

array([1, 3, 5, 7, 9])

In [105]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [102]:
array[:1, 2]

array([3.])

### Boolean indexing

In [113]:
print(a>3)
a[a>3]

[False False False  True  True  True  True  True  True]


array([4, 5, 6, 7, 8, 9])

### Fancy indexing