# NumPy quick reference

## Initial setup

In [1]:
import numpy as np

## Array creation

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.array([(1.5,2,3), (4,5,6)], dtype = float)

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [4]:
np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype = float)

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((2,3,4), dtype=np.float32)

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

In [7]:
np.arange(10, 25, 5)

array([10, 15, 20])

In [8]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [9]:
np.full((2,3), 7)

array([[7, 7, 7],
       [7, 7, 7]])

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random variables initialization

In [11]:
np.random.random((2,3))

array([[0.29172645, 0.06914398, 0.58781636],
       [0.96159658, 0.80058683, 0.20384035]])

In [12]:
np.random.randint(10, 20, (2,5))

array([[15, 15, 10, 11, 10],
       [12, 10, 17, 12, 15]])

In [13]:
np.random.normal(size=10)

array([-2.00716212, -0.7137781 ,  0.75752312,  0.55391711, -0.25390105,
       -0.80566977,  1.8322912 ,  1.30574867, -2.09883145,  0.45947669])

In [14]:
mean = 10
std = 3
np.random.normal(mean, std, 5)

array([ 3.82385382,  3.8876883 ,  4.15086183, 11.33480836, 10.05683204])

In [15]:
np.bool
np.int16
np.int32
np.uint16
np.uint32
np.float # Same than np.float64 
np.float32
np.float64
np.complex
np.string_
np.object # Python object

/home/david/anaconda3/envs/ml37/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.
/home/david/anaconda3/envs/ml37/lib/python3.7/site-packages/ipykernel_launcher.py:6: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  
/home/david/anaconda3/envs/ml37/li

object

## Array inspection

In [16]:
array = np.array([(1.5,2,3), (4,5,6)], dtype = float)
array

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [17]:
array.shape

(2, 3)

In [18]:
len(array)

2

In [19]:
array.ndim

2

In [20]:
array.size

6

In [21]:
array.dtype

dtype('float64')

In [22]:
array.dtype.name

'float64'

In [23]:
array.astype(np.float32)

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]], dtype=float32)

In [24]:
array.astype("float")

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

## Array reshape

In [25]:
a = np.linspace(1, 6, 6)

print(a)
print(a.shape)

[1. 2. 3. 4. 5. 6.]
(6,)


In [26]:
a.reshape(2, 3)
print(a.shape)

(6,)


In [27]:
b = a.reshape(2, 3)
print(b)
print(b.shape)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)


## Arithmetic operations

In [28]:
a = np.random.random((2,3))
b = np.random.random((2,3))

a + b

array([[0.53016091, 1.04513105, 1.17752699],
       [1.04876792, 1.20114672, 0.97383513]])

In [29]:
a + 2 * b

array([[0.6197531 , 1.92809668, 2.15064847],
       [1.61049694, 1.97160459, 1.72983458]])

In [30]:
np.add(a, b)

array([[0.53016091, 1.04513105, 1.17752699],
       [1.04876792, 1.20114672, 0.97383513]])

In [31]:
np.subtract(a, b)

array([[ 0.35097654, -0.72080019, -0.76871598],
       [-0.07469012, -0.33976902, -0.53816377]])

In [32]:
np.multiply(a, b)

array([[0.03947152, 0.1431865 , 0.19891139],
       [0.27358388, 0.33182762, 0.16468365]])

In [33]:
np.divide(a, b)

array([[4.91749041, 0.18365996, 0.21005137],
       [0.86703532, 0.55900377, 0.28814264]])

In [34]:
np.exp(a)

array([[1.55359053, 1.17605478, 1.22679552],
       [1.62748992, 1.53831683, 1.24338274]])

In [35]:
np.sqrt(a)

array([[0.66375351, 0.40269769, 0.45211227],
       [0.69788173, 0.65626889, 0.4667287 ]])

In [36]:
np.sin(a)

array([[0.42645395, 0.16145561, 0.20298507],
       [0.46801115, 0.41749685, 0.21611696]])

In [37]:
np.cos(a)

array([[0.90450927, 0.98687998, 0.97918183],
       [0.88372256, 0.90867837, 0.97636748]])

In [38]:
np.log(a)

array([[-0.81968883, -1.81913827, -1.5876495 ],
       [-0.71941128, -0.84236937, -1.52401426]])

In [39]:
np.dot(a, b.T)

array([[0.3815694 , 0.52695232],
       [0.63589891, 0.77009516]])

## Comparisons

In [40]:
a == b

array([[False, False, False],
       [False, False, False]])

In [41]:
a > 0.5

array([[False, False, False],
       [False, False, False]])

In [42]:
np.equal(a, b)

array([[False, False, False],
       [False, False, False]])

In [43]:
np.array_equal(a, b)

False

In [90]:
a = np.array([1,2,3])
b = np.array([1,0,3])

# get indices

np.where(a==b)

(array([0, 2]),)

## Aggregations

In [44]:
print(array)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [45]:
array.sum()

21.5

In [46]:
array.sum(axis=1) # Sum rows

array([ 6.5, 15. ])

In [47]:
array.sum(axis=0) # Sum columns

array([5.5, 7. , 9. ])

In [48]:
array.max()

6.0

In [49]:
array.max(axis=0) # Max per column

array([4., 5., 6.])

In [50]:
array.cumsum()

array([ 1.5,  3.5,  6.5, 10.5, 15.5, 21.5])

In [51]:
array.mean()

3.5833333333333335

In [52]:
array.std()

1.5920810978785667

## Stacking

In [67]:
# Horizontal stacking

a1 = np.array([[1,2,3], [4,5,6]])

a2 = np.array([[7,8,9], [10,11,12]])

np.hstack((a1, a2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [69]:
# Vertical stacking

np.vstack((a1, a2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Array copies

In [53]:
array.view() # View on array

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [54]:
array.copy() # Deep copy

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

## Array subsetting, slicing and indexing

### Subsetting

In [55]:
a = np.arange(1,10)
print(a)
print(array)

[1 2 3 4 5 6 7 8 9]
[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [56]:
a[2]

3

In [57]:
array[1,0]

4.0

### Slicing

In [58]:
a[1:4]

array([2, 3, 4])

In [59]:
a[:4]

array([1, 2, 3, 4])

In [60]:
a[4:]

array([5, 6, 7, 8, 9])

In [61]:
a[::2]

array([1, 3, 5, 7, 9])

In [62]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [63]:
array[:1, 2]

array([3.])

### Boolean indexing

In [64]:
print(a>3)
a[a>3]

[False False False  True  True  True  True  True  True]


array([4, 5, 6, 7, 8, 9])

### Fancy indexing

In [65]:
indices = [1,3,5]
print(a)
print(a[indices])

[1 2 3 4 5 6 7 8 9]
[2 4 6]


# NumPy exercises

These exercises have been taken from https://favtutor.com/blogs/numpy-exercises-python and https://www.machinelearningplus.com/python/101-numpy-exercises-python/.

1.- Check your NumPy version.

2.- Given two similar dimensional NumPy arrays, get a NumPy array output in which every element is an element-wise sum of the two NumPy arrays.

3.- Given two similar dimensional NumPy arrays (matrix), get a NumPy array output in which every element is equal to the original matrix multiplied by a scalar.

4.- Create a 4x4 matrix filled with fours in its diagonal.

5.- Convert a 1-D array to a 3-D array.

6.- Convert a binary NumPy array (containing only 0s and 1s) to a boolean array.

7.- Generate a sequence of numbers in the form of a NumPy array from 0 to 100 with gaps of 2 numbers, for example: 0, 2, 4 ....

8.- Output a sequence of equally gapped 5 numbers in the range 0 to 100 (both inclusive)

9.- Output a 5-by-5 array of random integers between 0 (inclusive) and 10 (exclusive).

10.- Output a 3-by-3 array of random numbers following normal distribution.

11.- Calculate the sine of an array of angles (in radians) using NumPy.

In [94]:
angles = np.array([3.14, 3.14/2, 6.28])

12.- Get all items between 5 and 10 from a.

In [96]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

13.- Reverse the rows of a 2D array.

14.- Reverse the columns of a 2D array.

15.- Normalize a 1-D array using the min-max, which is given by $\frac{x-x_{min}}{x_{max}-x_{min}}$

In [127]:
x = np.random.randint(-10, 10, size = 10)


[ -2 -10  -7  -7   9  -9  -3  -4  -7  -9]


# Solutions

## 1

In [66]:
import numpy as np

print(np.__version__)

1.20.1


## 2

In [71]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10,11,12],
              [13,14,15]])

c = a + b

print(c)

[[11 13 15]
 [17 19 21]]


## 3

In [73]:
a = np.array([[1,2,3],
              [4,5,6]])

b = 2*a # multiplying the numpy array a(matrix) by 2

print(b)

[[ 2  4  6]
 [ 8 10 12]]


## 4

In [75]:
i = np.eye(4) * 5

print(i)

[[5. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]


## 5

In [82]:
a = np.array([x for x in range(27)])

o = a.reshape((3,3,3))

print(o)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


## 6

In [83]:
a = np.array([[1, 0, 0],
              [1, 1, 1],
              [0, 0, 0]])

o = a.astype('bool')

print(o)

[[ True False False]
 [ True  True  True]
 [False False False]]


## 7

In [87]:
list_of_numbers = [x for x in range(0, 101, 2)]

o = np.array(list_of_numbers)

print(o)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [88]:
o = np.arange(0, 101, 2)

print(o)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


## 8

In [91]:
o = np.linspace(0, 100, 5)

print(o)

[  0.  25.  50.  75. 100.]


## 9

In [92]:
np.random.seed(123) # setting the seed

o = np.random.randint(0, 10, size = (5,5))

print(o)

[[2 2 6 1 3]
 [9 6 1 0 1]
 [9 0 0 9 3]
 [4 0 0 4 1]
 [7 3 2 4 7]]


## 10

In [93]:
np.random.seed(123) # setting the seed

o = np.random.normal(size = (3,3))

print(o)

[[-1.0856306   0.99734545  0.2829785 ]
 [-1.50629471 -0.57860025  1.65143654]
 [-2.42667924 -0.42891263  1.26593626]]


## 11

In [95]:
angles = np.array([3.14, 3.14/2, 6.28])

sine_of_angles = np.sin(angles)

print('Sine of the given array of angles = ', sine_of_angles)

Sine of the given array of angles =  [ 0.00159265  0.99999968 -0.0031853 ]


## 12

In [97]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 6,  9, 10])

In [98]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

## 13

In [103]:
arr = np.arange(9).reshape(3,3)

print(arr)

print(arr[::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


## 14

In [107]:
arr = np.arange(9).reshape(3,3)

print(arr)
print(arr[:, ::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


## 15

In [130]:
x = np.random.randint(-10, 10, size = 10)

Xmax, Xmin = x.max(), x.min()
X = (x - Xmin)/(Xmax - Xmin)

print(x)
print(X)

[6 6 4 5 7 6 4 4 1 5]
[0.83333333 0.83333333 0.5        0.66666667 1.         0.83333333
 0.5        0.5        0.         0.66666667]
